import './globals.css'
import Header from './components/Header'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='font.className'>
      <body className='bg-slate-950 text-slate-300'>
        <Header />
        
        {children}
      </body>
    </html>
  )
}
